### ISSUE TITLE
Enable press Enter input on form

### ISSUE THREAD

**Issue by martinlehoux** [paulcacheux/check-splitter#5]
Maybe you should use `<input type="number" step="0.01">`

![image](https://user-images.githubusercontent.com/26896369/80425728-1ad8a180-8899-11ea-86a4-0dcc22745eea.png)

**Comment by martinlehoux** [comment]
Thanks a lot for this amazing feature. I tested it, and it works perfect !

**Comment by paulcacheux** [comment]
Fixed by 28de59c4d443ccaaf018a3c85d44480ea1125786
